[package]
name = "h5read_rust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
hdf5 = "0.7.1"
libc = "0.2.99"

[build-dependencies]
cbindgen = "0.20.0"
